import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header";
import Rightbar from "./components/rightbarrpage/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div style={{ display: "flex", backgroundColor: "#FFFFF"  }}>
          <main style={{ flex: 1 }}>{children}</main>

          <aside >
            <Rightbar />
          </aside>
        </div>
            <footer
              className="w-full py-4 mt-8 text-center text-xs text-slate-400 border-t border-slate-200 bg-gray-300"
            >
              © 2024 <span className="font-semibold text-slate-500">Sakuyy</span>. All rights reserved.
            </footer>
      </body>
    </html>
  );
}
